//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raizen.SICCadastro.Rebate.Util.Arquivo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConstantesArquivo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantesArquivo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raizen.SICCadastro.Rebate.Util.Arquivo.ConstantesArquivo", typeof(ConstantesArquivo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        public static string AccountTypeK {
            get {
                return ResourceManager.GetString("AccountTypeK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string AccountTypeS {
            get {
                return ResourceManager.GetString("AccountTypeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string CanalDistribuicao {
            get {
                return ResourceManager.GetString("CanalDistribuicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R$.
        /// </summary>
        public static string ChaveMoeda {
            get {
                return ResourceManager.GetString("ChaveMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001.
        /// </summary>
        public static string CondicaoPagamento {
            get {
                return ResourceManager.GetString("CondicaoPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string FileRecordD {
            get {
                return ResourceManager.GetString("FileRecordD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string FileRecordG {
            get {
                return ResourceManager.GetString("FileRecordG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOTER.
        /// </summary>
        public static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEADER.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string LancamentoCredito {
            get {
                return ResourceManager.GetString("LancamentoCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string LancamentoDebito {
            get {
                return ResourceManager.GetString("LancamentoDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200007971.
        /// </summary>
        public static string NumeroAtribuicao {
            get {
                return ResourceManager.GetString("NumeroAtribuicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCMS.
        /// </summary>
        public static string SistemaLegado {
            get {
                return ResourceManager.GetString("SistemaLegado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REBATESIC.
        /// </summary>
        public static string TextoCabecalho {
            get {
                return ResourceManager.GetString("TextoCabecalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        public static string TipoDocumento {
            get {
                return ResourceManager.GetString("TipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB01.
        /// </summary>
        public static string Transacao {
            get {
                return ResourceManager.GetString("Transacao", resourceCulture);
            }
        }
    }
}
