//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raizen.SICCadastro.Rebate.BLL.Test.Msg {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raizen.SICCadastro.Rebate.BLL.Test.Msg.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos enviados pelo analista podem ser aprovados pelo gestor, revise a seleção atual!.
        /// </summary>
        internal static string AlertaAprovarGerenteSemEnviar {
            get {
                return ResourceManager.GetString("AlertaAprovarGerenteSemEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos que ainda não foram cancelados, enviados para pagamento ou pagos podem ser selecionados para esta ação!.
        /// </summary>
        internal static string AlertaBonificacaoCanceladaPagaEnviada {
            get {
                return ResourceManager.GetString("AlertaBonificacaoCanceladaPagaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculo não pagos podem ser selecionados para esta ação, revise a seleção atual!.
        /// </summary>
        internal static string AlertaBonificacaoPaga {
            get {
                return ResourceManager.GetString("AlertaBonificacaoPaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonificação não encontrada..
        /// </summary>
        internal static string AlertaCalculoPagamentoManual {
            get {
                return ResourceManager.GetString("AlertaCalculoPagamentoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inicial da consulta deve ser menor que a data final!.
        /// </summary>
        internal static string AlertaDataInicialMaiorDataFinal {
            get {
                return ResourceManager.GetString("AlertaDataInicialMaiorDataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serão exibidos somente os 20 primeiros resultados da consulta. Para visualizar maiores detalhes, execute a geração do arquivo excel..
        /// </summary>
        internal static string AlertaExibicaoPrimeiros {
            get {
                return ResourceManager.GetString("AlertaExibicaoPrimeiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Com os Filtros informados nenhum calculo foi localizado!.
        /// </summary>
        internal static string AlertaFiltroPagamentoBonificacaoVazio {
            get {
                return ResourceManager.GetString("AlertaFiltroPagamentoBonificacaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aditivo de Bonificação.
        /// </summary>
        internal static string AlertaGridDetalheAditivo {
            get {
                return ResourceManager.GetString("AlertaGridDetalheAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor informar o período para cálculo do aditivo!.
        /// </summary>
        internal static string AlertaInformePeriodoCalculoAditivo {
            get {
                return ResourceManager.GetString("AlertaInformePeriodoCalculoAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Calculo Rebate não informado.
        /// </summary>
        internal static string AlertaNumeroCalculoRebate {
            get {
                return ResourceManager.GetString("AlertaNumeroCalculoRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Rebate não informado..
        /// </summary>
        internal static string AlertaNumeroRebate {
            get {
                return ResourceManager.GetString("AlertaNumeroRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma observação para o pagamento manual..
        /// </summary>
        internal static string AlertaObservacaoPagtoManual {
            get {
                return ResourceManager.GetString("AlertaObservacaoPagtoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A seleção atual será perdida!.
        /// </summary>
        internal static string AlertaPerdaSelecao {
            get {
                return ResourceManager.GetString("AlertaPerdaSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, digite um período válido..
        /// </summary>
        internal static string AlertaPeriodoValido {
            get {
                return ResourceManager.GetString("AlertaPeriodoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe IBM, data inicial e data final do período para realizar a consulta!.
        /// </summary>
        internal static string AlertaPesquisaExtrato {
            get {
                return ResourceManager.GetString("AlertaPesquisaExtrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um tipo de rebate e um tipo de status cliente para a pesquisa!.
        /// </summary>
        internal static string AlertaPesquisaInfoCliente {
            get {
                return ResourceManager.GetString("AlertaPesquisaInfoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As datas inicial e final do período para a consulta devem ser informadas!.
        /// </summary>
        internal static string AlertaPesquisaPeriodo {
            get {
                return ResourceManager.GetString("AlertaPesquisaPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos período, IBM ou situação para a pesquisa!.
        /// </summary>
        internal static string AlertaPesquisaSemFiltros {
            get {
                return ResourceManager.GetString("AlertaPesquisaSemFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe ao menos um tipo de rebate para a pesquisa!.
        /// </summary>
        internal static string AlertaPesquisaTipoRebate {
            get {
                return ResourceManager.GetString("AlertaPesquisaTipoRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos não aprovados pelo analista podem ser selecionados, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReaprovarAnalista {
            get {
                return ResourceManager.GetString("AlertaReaprovarAnalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos não pagos podem ser selecionados, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReaprovarGerente {
            get {
                return ResourceManager.GetString("AlertaReaprovarGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos não enviados pelo analista podem ser selecionados, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReenviarGerente {
            get {
                return ResourceManager.GetString("AlertaReenviarGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos enviados pelo analista podem ser reprovados pelo gestor, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReprovarGerenteSemEnviar {
            get {
                return ResourceManager.GetString("AlertaReprovarGerenteSemEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente cálculos aprovados pelo analista podem ser enviados para aprovação do gestor, revise a seleção atual!.
        /// </summary>
        internal static string AlertaSelecaoEnviarSemAprovar {
            get {
                return ResourceManager.GetString("AlertaSelecaoEnviarSemAprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione ao menos uma linha!.
        /// </summary>
        internal static string AlertaSelecaoNula {
            get {
                return ResourceManager.GetString("AlertaSelecaoNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor selecionar um status..
        /// </summary>
        internal static string AlertaSelecionarStatus {
            get {
                return ResourceManager.GetString("AlertaSelecionarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O status atual é Informações Inconsistentes, por isso não é possível alterá-lo..
        /// </summary>
        internal static string AlertaStatusInformacoesInconsistentes {
            get {
                return ResourceManager.GetString("AlertaStatusInformacoesInconsistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente Rebates com status Pago podem ter o status alterado..
        /// </summary>
        internal static string AlertaStatusPago {
            get {
                return ResourceManager.GetString("AlertaStatusPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alteração de Status.
        /// </summary>
        internal static string AlteracaoStatus {
            get {
                return ResourceManager.GetString("AlteracaoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcular Aditivo.
        /// </summary>
        internal static string ConfirmarAditivo {
            get {
                return ResourceManager.GetString("ConfirmarAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprovar Bonificação.
        /// </summary>
        internal static string ConfirmarAprovar {
            get {
                return ResourceManager.GetString("ConfirmarAprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar Débitos.
        /// </summary>
        internal static string ConfirmarConsultaDebito {
            get {
                return ResourceManager.GetString("ConfirmarConsultaDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja confirmar a operação {0}?.
        /// </summary>
        internal static string ConfirmarDialog {
            get {
                return ResourceManager.GetString("ConfirmarDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar Para Aprovação Gerencial.
        /// </summary>
        internal static string ConfirmarEnviar {
            get {
                return ResourceManager.GetString("ConfirmarEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja consultar outras operações para este cálculo?.
        /// </summary>
        internal static string ConfirmarOutrasOperacoes {
            get {
                return ResourceManager.GetString("ConfirmarOutrasOperacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagamento Manual.
        /// </summary>
        internal static string ConfirmarPagamentoManual {
            get {
                return ResourceManager.GetString("ConfirmarPagamentoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalcular Bonificação (último período) {0}.
        /// </summary>
        internal static string ConfirmarRecalculo {
            get {
                return ResourceManager.GetString("ConfirmarRecalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprovar Bonificação.
        /// </summary>
        internal static string ConfirmarReprovar {
            get {
                return ResourceManager.GetString("ConfirmarReprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo Retroativo.
        /// </summary>
        internal static string ConfirmarRetroativo {
            get {
                return ResourceManager.GetString("ConfirmarRetroativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar o cálculo do aditivo.
        /// </summary>
        internal static string ErroAditivo {
            get {
                return ResourceManager.GetString("ErroAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível alterar o status do cliente..
        /// </summary>
        internal static string ErroAlteracaoStatus {
            get {
                return ResourceManager.GetString("ErroAlteracaoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar o cálculo retroativo.
        /// </summary>
        internal static string ErroCalculoRetroativo {
            get {
                return ResourceManager.GetString("ErroCalculoRetroativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebate não encontrado para o IBM informado!.
        /// </summary>
        internal static string ErroConsultaIBM {
            get {
                return ResourceManager.GetString("ErroConsultaIBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível executar a consulta..
        /// </summary>
        internal static string ErroConsultarBonificacao {
            get {
                return ResourceManager.GetString("ErroConsultarBonificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível exibir os detalhes deste cálculo..
        /// </summary>
        internal static string ErroConsultarDetalhe {
            get {
                return ResourceManager.GetString("ErroConsultarDetalhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível exibir os detalhes deste cliente..
        /// </summary>
        internal static string ErroConsultarDetalheCliente {
            get {
                return ResourceManager.GetString("ErroConsultarDetalheCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível executar a ação solicitada..
        /// </summary>
        internal static string ErroGenerico {
            get {
                return ResourceManager.GetString("ErroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existem registros para serem exibidos, por favor realize uma consulta!.
        /// </summary>
        internal static string ErroGerarExcel {
            get {
                return ResourceManager.GetString("ErroGerarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel executar o pagamento manual.
        /// </summary>
        internal static string ErroPagamentoManual {
            get {
                return ResourceManager.GetString("ErroPagamentoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar o período para recálculo..
        /// </summary>
        internal static string ErroPeriodoRecalculo {
            get {
                return ResourceManager.GetString("ErroPeriodoRecalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível realizar o Recálculo do último período..
        /// </summary>
        internal static string ErroRecalcular {
            get {
                return ResourceManager.GetString("ErroRecalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonificação Recalculada com sucesso!.
        /// </summary>
        internal static string MsgRecalculoSucesso {
            get {
                return ResourceManager.GetString("MsgRecalculoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo Retroativo realizado com sucesso!.
        /// </summary>
        internal static string MsgRetroativoSucesso {
            get {
                return ResourceManager.GetString("MsgRetroativoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status alterado com sucesso!.
        /// </summary>
        internal static string MsgStatusSucesso {
            get {
                return ResourceManager.GetString("MsgStatusSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cálculo do Aditivo realizado com sucesso!.
        /// </summary>
        internal static string MsgSucessoAditivo {
            get {
                return ResourceManager.GetString("MsgSucessoAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso!.
        /// </summary>
        internal static string MsgSucessoPagtoManual {
            get {
                return ResourceManager.GetString("MsgSucessoPagtoManual", resourceCulture);
            }
        }
    }
}
