//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raizen.SICCadastro.Rebate.SAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services-dev.cosan.com.br/UserSystemServices/wsUserSystem.asmx")]
        public string Raizen_SICCadastro_Rebate_SAL_UserSystem_wsUserSystem {
            get {
                return ((string)(this["Raizen_SICCadastro_Rebate_SAL_UserSystem_wsUserSystem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cpsvsappid01.cosan.rede:50000/XISOAPAdapter/MessageServlet?senderParty=&se" +
            "nderService=SIC&receiverParty=&receiverService=&interface=Credito_Out&interfaceN" +
            "amespace=urn%3Aminhati.com.br%2Fsicle%2Fcredito")]
        public string Raizen_SICCadastro_Rebate_SAL_wsCredito_Credito_OutService {
            get {
                return ((string)(this["Raizen_SICCadastro_Rebate_SAL_wsCredito_Credito_OutService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cpsvsappid01.cosan.rede:50000/XISOAPAdapter/MessageServlet?senderParty=&se" +
            "nderService=SIC&receiverParty=&receiverService=&interface=SIC_SyncOutAtualizaDoc" +
            "Contabil&interfaceNamespace=urn%3Asic.raizen.com%2Fxi%2Ffi")]
        public string Raizen_SICCadastro_Rebate_SAL_wsAtualizaDocContabil_SIC_SyncOutAtualizaDocContabilService {
            get {
                return ((string)(this["Raizen_SICCadastro_Rebate_SAL_wsAtualizaDocContabil_SIC_SyncOutAtualizaDocContabi" +
                    "lService"]));
            }
        }
    }
}
