//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raizen.SICCadastro.Rebate.WebSite.Msg {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raizen.SICCadastro.Rebate.WebSite.Msg.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos enviados pelo analista podem ser aprovados pelo gestor, revise a seleção atual!.
        /// </summary>
        internal static string AlertaAprovarGerenteSemEnviar {
            get {
                return ResourceManager.GetString("AlertaAprovarGerenteSemEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos que ainda não foram cancelados, enviados para pagamento ou pagos podem ser selecionados para esta ação!.
        /// </summary>
        internal static string AlertaBonificacaoCanceladaPagaEnviada {
            get {
                return ResourceManager.GetString("AlertaBonificacaoCanceladaPagaEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculo não pagos podem ser selecionados para esta ação, revise a seleção atual!.
        /// </summary>
        internal static string AlertaBonificacaoPaga {
            get {
                return ResourceManager.GetString("AlertaBonificacaoPaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bonificação não encontrada..
        /// </summary>
        internal static string AlertaCalculoPagamentoManual {
            get {
                return ResourceManager.GetString("AlertaCalculoPagamentoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data inicial da consulta deve ser menor que a data final!.
        /// </summary>
        internal static string AlertaDataInicialMaiorDataFinal {
            get {
                return ResourceManager.GetString("AlertaDataInicialMaiorDataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serão exibidos somente os 20 primeiros resultados da consulta. Para visualizar maiores detalhes, execute a geração do arquivo excel..
        /// </summary>
        internal static string AlertaExibicaoPrimeiros {
            get {
                return ResourceManager.GetString("AlertaExibicaoPrimeiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Com os Filtros informados nenhum calculo foi localizado!.
        /// </summary>
        internal static string AlertaFiltroPagamentoBonificacaoVazio {
            get {
                return ResourceManager.GetString("AlertaFiltroPagamentoBonificacaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aditivo de Bonificação.
        /// </summary>
        internal static string AlertaGridDetalheAditivo {
            get {
                return ResourceManager.GetString("AlertaGridDetalheAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor informar o período para cálculo do aditivo!.
        /// </summary>
        internal static string AlertaInformePeriodoCalculoAditivo {
            get {
                return ResourceManager.GetString("AlertaInformePeriodoCalculoAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número Calculo Rebate não informado.
        /// </summary>
        internal static string AlertaNumeroCalculoRebate {
            get {
                return ResourceManager.GetString("AlertaNumeroCalculoRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número Rebate não informado..
        /// </summary>
        internal static string AlertaNumeroRebate {
            get {
                return ResourceManager.GetString("AlertaNumeroRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe uma observação para o pagamento manual..
        /// </summary>
        internal static string AlertaObservacaoPagtoManual {
            get {
                return ResourceManager.GetString("AlertaObservacaoPagtoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A seleção atual será perdida!.
        /// </summary>
        internal static string AlertaPerdaSelecao {
            get {
                return ResourceManager.GetString("AlertaPerdaSelecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, digite um período válido..
        /// </summary>
        internal static string AlertaPeriodoValido {
            get {
                return ResourceManager.GetString("AlertaPeriodoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe IBM, data inicial e data final do período para realizar a consulta!.
        /// </summary>
        internal static string AlertaPesquisaExtrato {
            get {
                return ResourceManager.GetString("AlertaPesquisaExtrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe ao menos um tipo de rebate e um tipo de status cliente para a pesquisa!.
        /// </summary>
        internal static string AlertaPesquisaInfoCliente {
            get {
                return ResourceManager.GetString("AlertaPesquisaInfoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As datas inicial e final do período para a consulta devem ser informadas!.
        /// </summary>
        internal static string AlertaPesquisaPeriodo {
            get {
                return ResourceManager.GetString("AlertaPesquisaPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe ao menos período, IBM ou situação para a pesquisa!.
        /// </summary>
        internal static string AlertaPesquisaSemFiltros {
            get {
                return ResourceManager.GetString("AlertaPesquisaSemFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informe ao menos um tipo de rebate para a pesquisa!.
        /// </summary>
        internal static string AlertaPesquisaTipoRebate {
            get {
                return ResourceManager.GetString("AlertaPesquisaTipoRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos não aprovados pelo analista podem ser selecionados, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReaprovarAnalista {
            get {
                return ResourceManager.GetString("AlertaReaprovarAnalista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos não pagos podem ser selecionados, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReaprovarGerente {
            get {
                return ResourceManager.GetString("AlertaReaprovarGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos não enviados pelo analista podem ser selecionados, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReenviarGerente {
            get {
                return ResourceManager.GetString("AlertaReenviarGerente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos enviados pelo analista podem ser reprovados pelo gestor, revise a seleção atual!.
        /// </summary>
        internal static string AlertaReprovarGerenteSemEnviar {
            get {
                return ResourceManager.GetString("AlertaReprovarGerenteSemEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente cálculos aprovados pelo analista podem ser enviados para aprovação do gestor, revise a seleção atual!.
        /// </summary>
        internal static string AlertaSelecaoEnviarSemAprovar {
            get {
                return ResourceManager.GetString("AlertaSelecaoEnviarSemAprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione ao menos uma linha!.
        /// </summary>
        internal static string AlertaSelecaoNula {
            get {
                return ResourceManager.GetString("AlertaSelecaoNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor selecionar um status..
        /// </summary>
        internal static string AlertaSelecionarStatus {
            get {
                return ResourceManager.GetString("AlertaSelecionarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O status atual é Informações Inconsistentes, por isso não é possível alterá-lo..
        /// </summary>
        internal static string AlertaStatusInformacoesInconsistentes {
            get {
                return ResourceManager.GetString("AlertaStatusInformacoesInconsistentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Somente Rebates com status Pago podem ter o status alterado..
        /// </summary>
        internal static string AlertaStatusPago {
            get {
                return ResourceManager.GetString("AlertaStatusPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alteração de Status.
        /// </summary>
        internal static string AlteracaoStatus {
            get {
                return ResourceManager.GetString("AlteracaoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Calcular Aditivo.
        /// </summary>
        internal static string ConfirmarAditivo {
            get {
                return ResourceManager.GetString("ConfirmarAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aprovar Bonificação.
        /// </summary>
        internal static string ConfirmarAprovar {
            get {
                return ResourceManager.GetString("ConfirmarAprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consultar Débitos.
        /// </summary>
        internal static string ConfirmarConsultaDebito {
            get {
                return ResourceManager.GetString("ConfirmarConsultaDebito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja confirmar a operação {0}?.
        /// </summary>
        internal static string ConfirmarDialog {
            get {
                return ResourceManager.GetString("ConfirmarDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enviar Para Aprovação Gerencial.
        /// </summary>
        internal static string ConfirmarEnviar {
            get {
                return ResourceManager.GetString("ConfirmarEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja consultar outras operações para este cálculo?.
        /// </summary>
        internal static string ConfirmarOutrasOperacoes {
            get {
                return ResourceManager.GetString("ConfirmarOutrasOperacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pagamento Manual.
        /// </summary>
        internal static string ConfirmarPagamentoManual {
            get {
                return ResourceManager.GetString("ConfirmarPagamentoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recalcular Bonificação (último período) {0}.
        /// </summary>
        internal static string ConfirmarRecalculo {
            get {
                return ResourceManager.GetString("ConfirmarRecalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reprovar Bonificação.
        /// </summary>
        internal static string ConfirmarReprovar {
            get {
                return ResourceManager.GetString("ConfirmarReprovar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cálculo Retroativo.
        /// </summary>
        internal static string ConfirmarRetroativo {
            get {
                return ResourceManager.GetString("ConfirmarRetroativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível realizar o cálculo do aditivo.
        /// </summary>
        internal static string ErroAditivo {
            get {
                return ResourceManager.GetString("ErroAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível alterar o status do cliente..
        /// </summary>
        internal static string ErroAlteracaoStatus {
            get {
                return ResourceManager.GetString("ErroAlteracaoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível realizar o cálculo retroativo.
        /// </summary>
        internal static string ErroCalculoRetroativo {
            get {
                return ResourceManager.GetString("ErroCalculoRetroativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rebate não encontrado para o IBM informado!.
        /// </summary>
        internal static string ErroConsultaIBM {
            get {
                return ResourceManager.GetString("ErroConsultaIBM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível executar a consulta..
        /// </summary>
        internal static string ErroConsultarBonificacao {
            get {
                return ResourceManager.GetString("ErroConsultarBonificacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível exibir os detalhes deste cálculo..
        /// </summary>
        internal static string ErroConsultarDetalhe {
            get {
                return ResourceManager.GetString("ErroConsultarDetalhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível exibir os detalhes deste cliente..
        /// </summary>
        internal static string ErroConsultarDetalheCliente {
            get {
                return ResourceManager.GetString("ErroConsultarDetalheCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível executar a ação solicitada..
        /// </summary>
        internal static string ErroGenerico {
            get {
                return ResourceManager.GetString("ErroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existem registros para serem exibidos, por favor realize uma consulta!.
        /// </summary>
        internal static string ErroGerarExcel {
            get {
                return ResourceManager.GetString("ErroGerarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel executar o pagamento manual.
        /// </summary>
        internal static string ErroPagamentoManual {
            get {
                return ResourceManager.GetString("ErroPagamentoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar o período para recálculo..
        /// </summary>
        internal static string ErroPeriodoRecalculo {
            get {
                return ResourceManager.GetString("ErroPeriodoRecalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível realizar o Recálculo do último período..
        /// </summary>
        internal static string ErroRecalcular {
            get {
                return ResourceManager.GetString("ErroRecalcular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deseja realmente retornar a página de listagem?.
        /// </summary>
        internal static string MsgBotaoVoltar {
            get {
                return ResourceManager.GetString("MsgBotaoVoltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro na operação de Restrição. Tente mais tarde ou entre em contato com o administrador..
        /// </summary>
        internal static string MsgErroRestricao {
            get {
                return ResourceManager.GetString("MsgErroRestricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro na operação de Restrição. O IBM já está cadastrado com Restrição..
        /// </summary>
        internal static string MsgErroRestricaoIBMExistente {
            get {
                return ResourceManager.GetString("MsgErroRestricaoIBMExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro na operação de Tipo de Restrição. Tente mais tarde ou entre em contato com o administrador..
        /// </summary>
        internal static string MsgErroTipoRestricao {
            get {
                return ResourceManager.GetString("MsgErroTipoRestricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este tipo de restrição não pode ser excluído, pois está vinculado a uma Restrição de um IBM..
        /// </summary>
        internal static string MsgErroTipoRestricaoEmUso {
            get {
                return ResourceManager.GetString("MsgErroTipoRestricaoEmUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bonificação Recalculada com sucesso!.
        /// </summary>
        internal static string MsgRecalculoSucesso {
            get {
                return ResourceManager.GetString("MsgRecalculoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Restrição foi excluída com sucesso..
        /// </summary>
        internal static string MsgRestricaoExcluirSucesso {
            get {
                return ResourceManager.GetString("MsgRestricaoExcluirSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Restrição foi gravada com sucesso..
        /// </summary>
        internal static string MsgRestricaoSucesso {
            get {
                return ResourceManager.GetString("MsgRestricaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os campos IBM e ao menos um tipo de restrição são obrigatórios..
        /// </summary>
        internal static string MsgRestricaoVazio {
            get {
                return ResourceManager.GetString("MsgRestricaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cálculo Retroativo realizado com sucesso!.
        /// </summary>
        internal static string MsgRetroativoSucesso {
            get {
                return ResourceManager.GetString("MsgRetroativoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status alterado com sucesso!.
        /// </summary>
        internal static string MsgStatusSucesso {
            get {
                return ResourceManager.GetString("MsgStatusSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cálculo do Aditivo realizado com sucesso!.
        /// </summary>
        internal static string MsgSucessoAditivo {
            get {
                return ResourceManager.GetString("MsgSucessoAditivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação realizada com sucesso!.
        /// </summary>
        internal static string MsgSucessoPagtoManual {
            get {
                return ResourceManager.GetString("MsgSucessoPagtoManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Tipo de Restrição foi excluído com sucesso..
        /// </summary>
        internal static string MsgTipoRestricaoExcluirSucesso {
            get {
                return ResourceManager.GetString("MsgTipoRestricaoExcluirSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Tipo de Restrição foi gravado com sucesso..
        /// </summary>
        internal static string MsgTipoRestricaoSucesso {
            get {
                return ResourceManager.GetString("MsgTipoRestricaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Tipo de Restrição não pode ser vazio..
        /// </summary>
        internal static string MsgTipoRestricaoVazio {
            get {
                return ResourceManager.GetString("MsgTipoRestricaoVazio", resourceCulture);
            }
        }
    }
}
