//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.raizen.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebitoRbc", Namespace="http://www.raizen.com/")]
    [System.SerializableAttribute()]
    public partial class DebitoRbc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NrClientePagadorField;
        
        private System.DateTime DtVencimentoOriginalField;
        
        private int DiasVencidosField;
        
        private System.Nullable<decimal> VlMontanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NrClientePagador {
            get {
                return this.NrClientePagadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NrClientePagadorField, value) != true)) {
                    this.NrClientePagadorField = value;
                    this.RaisePropertyChanged("NrClientePagador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DtVencimentoOriginal {
            get {
                return this.DtVencimentoOriginalField;
            }
            set {
                if ((this.DtVencimentoOriginalField.Equals(value) != true)) {
                    this.DtVencimentoOriginalField = value;
                    this.RaisePropertyChanged("DtVencimentoOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DiasVencidos {
            get {
                return this.DiasVencidosField;
            }
            set {
                if ((this.DiasVencidosField.Equals(value) != true)) {
                    this.DiasVencidosField = value;
                    this.RaisePropertyChanged("DiasVencidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> VlMontante {
            get {
                return this.VlMontanteField;
            }
            set {
                if ((this.VlMontanteField.Equals(value) != true)) {
                    this.VlMontanteField = value;
                    this.RaisePropertyChanged("VlMontante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.raizen.com/", ConfigurationName="wsConsultarDebitos.wsConsultaDebitosSoap")]
    public interface wsConsultaDebitosSoap {
        
        // CODEGEN: Generating message contract since element name ibm from namespace http://www.raizen.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.raizen.com/ObterListaIbmPagadorPorIbmControlador", ReplyAction="*")]
        Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorResponse ObterListaIbmPagadorPorIbmControlador(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequest request);
        
        // CODEGEN: Generating message contract since element name ibm from namespace http://www.raizen.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.raizen.com/ObterListaDebitosPorIbmPagador", ReplyAction="*")]
        Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorResponse ObterListaDebitosPorIbmPagador(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequest request);
        
        // CODEGEN: Generating message contract since element name ibm from namespace http://www.raizen.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.raizen.com/ObterListaDebitosPorIbmControlador", ReplyAction="*")]
        Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorResponse ObterListaDebitosPorIbmControlador(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaIbmPagadorPorIbmControladorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaIbmPagadorPorIbmControlador", Namespace="http://www.raizen.com/", Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequestBody Body;
        
        public ObterListaIbmPagadorPorIbmControladorRequest() {
        }
        
        public ObterListaIbmPagadorPorIbmControladorRequest(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.raizen.com/")]
    public partial class ObterListaIbmPagadorPorIbmControladorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ibm;
        
        public ObterListaIbmPagadorPorIbmControladorRequestBody() {
        }
        
        public ObterListaIbmPagadorPorIbmControladorRequestBody(string ibm) {
            this.ibm = ibm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaIbmPagadorPorIbmControladorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaIbmPagadorPorIbmControladorResponse", Namespace="http://www.raizen.com/", Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorResponseBody Body;
        
        public ObterListaIbmPagadorPorIbmControladorResponse() {
        }
        
        public ObterListaIbmPagadorPorIbmControladorResponse(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.raizen.com/")]
    public partial class ObterListaIbmPagadorPorIbmControladorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ArrayOfString ObterListaIbmPagadorPorIbmControladorResult;
        
        public ObterListaIbmPagadorPorIbmControladorResponseBody() {
        }
        
        public ObterListaIbmPagadorPorIbmControladorResponseBody(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ArrayOfString ObterListaIbmPagadorPorIbmControladorResult) {
            this.ObterListaIbmPagadorPorIbmControladorResult = ObterListaIbmPagadorPorIbmControladorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDebitosPorIbmPagadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDebitosPorIbmPagador", Namespace="http://www.raizen.com/", Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequestBody Body;
        
        public ObterListaDebitosPorIbmPagadorRequest() {
        }
        
        public ObterListaDebitosPorIbmPagadorRequest(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.raizen.com/")]
    public partial class ObterListaDebitosPorIbmPagadorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ibm;
        
        public ObterListaDebitosPorIbmPagadorRequestBody() {
        }
        
        public ObterListaDebitosPorIbmPagadorRequestBody(string ibm) {
            this.ibm = ibm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDebitosPorIbmPagadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDebitosPorIbmPagadorResponse", Namespace="http://www.raizen.com/", Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorResponseBody Body;
        
        public ObterListaDebitosPorIbmPagadorResponse() {
        }
        
        public ObterListaDebitosPorIbmPagadorResponse(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.raizen.com/")]
    public partial class ObterListaDebitosPorIbmPagadorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.DebitoRbc[] ObterListaDebitosPorIbmPagadorResult;
        
        public ObterListaDebitosPorIbmPagadorResponseBody() {
        }
        
        public ObterListaDebitosPorIbmPagadorResponseBody(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.DebitoRbc[] ObterListaDebitosPorIbmPagadorResult) {
            this.ObterListaDebitosPorIbmPagadorResult = ObterListaDebitosPorIbmPagadorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDebitosPorIbmControladorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDebitosPorIbmControlador", Namespace="http://www.raizen.com/", Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequestBody Body;
        
        public ObterListaDebitosPorIbmControladorRequest() {
        }
        
        public ObterListaDebitosPorIbmControladorRequest(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.raizen.com/")]
    public partial class ObterListaDebitosPorIbmControladorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ibm;
        
        public ObterListaDebitosPorIbmControladorRequestBody() {
        }
        
        public ObterListaDebitosPorIbmControladorRequestBody(string ibm) {
            this.ibm = ibm;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDebitosPorIbmControladorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDebitosPorIbmControladorResponse", Namespace="http://www.raizen.com/", Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorResponseBody Body;
        
        public ObterListaDebitosPorIbmControladorResponse() {
        }
        
        public ObterListaDebitosPorIbmControladorResponse(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.raizen.com/")]
    public partial class ObterListaDebitosPorIbmControladorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.DebitoRbc[] ObterListaDebitosPorIbmControladorResult;
        
        public ObterListaDebitosPorIbmControladorResponseBody() {
        }
        
        public ObterListaDebitosPorIbmControladorResponseBody(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.DebitoRbc[] ObterListaDebitosPorIbmControladorResult) {
            this.ObterListaDebitosPorIbmControladorResult = ObterListaDebitosPorIbmControladorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsConsultaDebitosSoapChannel : Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsConsultaDebitosSoapClient : System.ServiceModel.ClientBase<Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap>, Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap {
        
        public wsConsultaDebitosSoapClient() {
        }
        
        public wsConsultaDebitosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsConsultaDebitosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsConsultaDebitosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsConsultaDebitosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorResponse Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap.ObterListaIbmPagadorPorIbmControlador(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequest request) {
            return base.Channel.ObterListaIbmPagadorPorIbmControlador(request);
        }
        
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ArrayOfString ObterListaIbmPagadorPorIbmControlador(string ibm) {
            Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequest inValue = new Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequest();
            inValue.Body = new Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorRequestBody();
            inValue.Body.ibm = ibm;
            Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaIbmPagadorPorIbmControladorResponse retVal = ((Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap)(this)).ObterListaIbmPagadorPorIbmControlador(inValue);
            return retVal.Body.ObterListaIbmPagadorPorIbmControladorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorResponse Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap.ObterListaDebitosPorIbmPagador(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequest request) {
            return base.Channel.ObterListaDebitosPorIbmPagador(request);
        }
        
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.DebitoRbc[] ObterListaDebitosPorIbmPagador(string ibm) {
            Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequest inValue = new Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequest();
            inValue.Body = new Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorRequestBody();
            inValue.Body.ibm = ibm;
            Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmPagadorResponse retVal = ((Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap)(this)).ObterListaDebitosPorIbmPagador(inValue);
            return retVal.Body.ObterListaDebitosPorIbmPagadorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorResponse Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap.ObterListaDebitosPorIbmControlador(Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequest request) {
            return base.Channel.ObterListaDebitosPorIbmControlador(request);
        }
        
        public Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.DebitoRbc[] ObterListaDebitosPorIbmControlador(string ibm) {
            Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequest inValue = new Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequest();
            inValue.Body = new Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorRequestBody();
            inValue.Body.ibm = ibm;
            Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.ObterListaDebitosPorIbmControladorResponse retVal = ((Raizen.SICCadastro.Rebate.SAL.wsConsultarDebitos.wsConsultaDebitosSoap)(this)).ObterListaDebitosPorIbmControlador(inValue);
            return retVal.Body.ObterListaDebitosPorIbmControladorResult;
        }
    }
}
