//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Raizen.SICCadastro.Rebate.SAL.wsCredito {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Credito_OutBinding", Namespace="urn:minhati.com.br/sicle/credito")]
    public partial class Credito_OutService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Consultar_SyncOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Credito_OutService() {
            this.Url = global::Raizen.SICCadastro.Rebate.SAL.Properties.Settings.Default.Raizen_SICCadastro_Rebate_SAL_wsCredito_Credito_OutService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Consultar_SyncCompletedEventHandler Consultar_SyncCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ConsultarResponse", Namespace="urn:minhati.com.br/sicle/credito")]
        public ConsultarResponse Consultar_Sync([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:minhati.com.br/sicle/credito")] ConsultarRequest ConsultarRequest) {
            object[] results = this.Invoke("Consultar_Sync", new object[] {
                        ConsultarRequest});
            return ((ConsultarResponse)(results[0]));
        }
        
        /// <remarks/>
        public void Consultar_SyncAsync(ConsultarRequest ConsultarRequest) {
            this.Consultar_SyncAsync(ConsultarRequest, null);
        }
        
        /// <remarks/>
        public void Consultar_SyncAsync(ConsultarRequest ConsultarRequest, object userState) {
            if ((this.Consultar_SyncOperationCompleted == null)) {
                this.Consultar_SyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultar_SyncOperationCompleted);
            }
            this.InvokeAsync("Consultar_Sync", new object[] {
                        ConsultarRequest}, this.Consultar_SyncOperationCompleted, userState);
        }
        
        private void OnConsultar_SyncOperationCompleted(object arg) {
            if ((this.Consultar_SyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Consultar_SyncCompleted(this, new Consultar_SyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:minhati.com.br/sicle/credito")]
    public partial class ConsultarRequest {
        
        private string ambienteField;
        
        private string dataField;
        
        private string areaCreditoField;
        
        private string clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaCredito {
            get {
                return this.areaCreditoField;
            }
            set {
                this.areaCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:minhati.com.br/sicle/credito")]
    public partial class ConsultarResponse {
        
        private string moedaField;
        
        private decimal limCreditoField;
        
        private bool limCreditoFieldSpecified;
        
        private decimal excLimCredField;
        
        private bool excLimCredFieldSpecified;
        
        private ConsultarResponseCliente clienteField;
        
        private string contaField;
        
        private decimal vlPendenteField;
        
        private bool vlPendenteFieldSpecified;
        
        private decimal vlCredPendField;
        
        private bool vlCredPendFieldSpecified;
        
        private decimal totDividasField;
        
        private bool totDividasFieldSpecified;
        
        private decimal vlCreditoField;
        
        private bool vlCreditoFieldSpecified;
        
        private decimal compEspecialField;
        
        private bool compEspecialFieldSpecified;
        
        private string esgotamentoField;
        
        private decimal totCompField;
        
        private bool totCompFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Moeda {
            get {
                return this.moedaField;
            }
            set {
                this.moedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LimCredito {
            get {
                return this.limCreditoField;
            }
            set {
                this.limCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimCreditoSpecified {
            get {
                return this.limCreditoFieldSpecified;
            }
            set {
                this.limCreditoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ExcLimCred {
            get {
                return this.excLimCredField;
            }
            set {
                this.excLimCredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExcLimCredSpecified {
            get {
                return this.excLimCredFieldSpecified;
            }
            set {
                this.excLimCredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultarResponseCliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Conta {
            get {
                return this.contaField;
            }
            set {
                this.contaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VlPendente {
            get {
                return this.vlPendenteField;
            }
            set {
                this.vlPendenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VlPendenteSpecified {
            get {
                return this.vlPendenteFieldSpecified;
            }
            set {
                this.vlPendenteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VlCredPend {
            get {
                return this.vlCredPendField;
            }
            set {
                this.vlCredPendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VlCredPendSpecified {
            get {
                return this.vlCredPendFieldSpecified;
            }
            set {
                this.vlCredPendFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TotDividas {
            get {
                return this.totDividasField;
            }
            set {
                this.totDividasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotDividasSpecified {
            get {
                return this.totDividasFieldSpecified;
            }
            set {
                this.totDividasFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VlCredito {
            get {
                return this.vlCreditoField;
            }
            set {
                this.vlCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VlCreditoSpecified {
            get {
                return this.vlCreditoFieldSpecified;
            }
            set {
                this.vlCreditoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CompEspecial {
            get {
                return this.compEspecialField;
            }
            set {
                this.compEspecialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompEspecialSpecified {
            get {
                return this.compEspecialFieldSpecified;
            }
            set {
                this.compEspecialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Esgotamento {
            get {
                return this.esgotamentoField;
            }
            set {
                this.esgotamentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TotComp {
            get {
                return this.totCompField;
            }
            set {
                this.totCompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotCompSpecified {
            get {
                return this.totCompFieldSpecified;
            }
            set {
                this.totCompFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:minhati.com.br/sicle/credito")]
    public partial class ConsultarResponseCliente {
        
        private string clienteField;
        
        private string areaCredField;
        
        private decimal limCredField;
        
        private bool limCredFieldSpecified;
        
        private string contaField;
        
        private decimal totOrdemField;
        
        private bool totOrdemFieldSpecified;
        
        private decimal totDivRecbField;
        
        private bool totDivRecbFieldSpecified;
        
        private decimal compEspecialField;
        
        private bool compEspecialFieldSpecified;
        
        private string dtExcedidoField;
        
        private string nomRespField;
        
        private string dtCriacaoField;
        
        private string clRiscoField;
        
        private string dtVerifIntField;
        
        private string bloqueioField;
        
        private string grpRespField;
        
        private string verSeguinteField;
        
        private string numCredField;
        
        private string dtVerifExtField;
        
        private string dtUltModField;
        
        private string dtUltTextoField;
        
        private string grpCreditoField;
        
        private string nmUltModField;
        
        private string dtReferenciaField;
        
        private string grpClienteField;
        
        private string dtPagmtoField;
        
        private decimal vlultPagmtoField;
        
        private bool vlultPagmtoFieldSpecified;
        
        private string moeUltPagmtoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AreaCred {
            get {
                return this.areaCredField;
            }
            set {
                this.areaCredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal LimCred {
            get {
                return this.limCredField;
            }
            set {
                this.limCredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LimCredSpecified {
            get {
                return this.limCredFieldSpecified;
            }
            set {
                this.limCredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Conta {
            get {
                return this.contaField;
            }
            set {
                this.contaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TotOrdem {
            get {
                return this.totOrdemField;
            }
            set {
                this.totOrdemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotOrdemSpecified {
            get {
                return this.totOrdemFieldSpecified;
            }
            set {
                this.totOrdemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TotDivRecb {
            get {
                return this.totDivRecbField;
            }
            set {
                this.totDivRecbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotDivRecbSpecified {
            get {
                return this.totDivRecbFieldSpecified;
            }
            set {
                this.totDivRecbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CompEspecial {
            get {
                return this.compEspecialField;
            }
            set {
                this.compEspecialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompEspecialSpecified {
            get {
                return this.compEspecialFieldSpecified;
            }
            set {
                this.compEspecialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtExcedido {
            get {
                return this.dtExcedidoField;
            }
            set {
                this.dtExcedidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NomResp {
            get {
                return this.nomRespField;
            }
            set {
                this.nomRespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtCriacao {
            get {
                return this.dtCriacaoField;
            }
            set {
                this.dtCriacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClRisco {
            get {
                return this.clRiscoField;
            }
            set {
                this.clRiscoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtVerifInt {
            get {
                return this.dtVerifIntField;
            }
            set {
                this.dtVerifIntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bloqueio {
            get {
                return this.bloqueioField;
            }
            set {
                this.bloqueioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrpResp {
            get {
                return this.grpRespField;
            }
            set {
                this.grpRespField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VerSeguinte {
            get {
                return this.verSeguinteField;
            }
            set {
                this.verSeguinteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NumCred {
            get {
                return this.numCredField;
            }
            set {
                this.numCredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtVerifExt {
            get {
                return this.dtVerifExtField;
            }
            set {
                this.dtVerifExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtUltMod {
            get {
                return this.dtUltModField;
            }
            set {
                this.dtUltModField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtUltTexto {
            get {
                return this.dtUltTextoField;
            }
            set {
                this.dtUltTextoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrpCredito {
            get {
                return this.grpCreditoField;
            }
            set {
                this.grpCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NmUltMod {
            get {
                return this.nmUltModField;
            }
            set {
                this.nmUltModField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtReferencia {
            get {
                return this.dtReferenciaField;
            }
            set {
                this.dtReferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrpCliente {
            get {
                return this.grpClienteField;
            }
            set {
                this.grpClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DtPagmto {
            get {
                return this.dtPagmtoField;
            }
            set {
                this.dtPagmtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal VlultPagmto {
            get {
                return this.vlultPagmtoField;
            }
            set {
                this.vlultPagmtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VlultPagmtoSpecified {
            get {
                return this.vlultPagmtoFieldSpecified;
            }
            set {
                this.vlultPagmtoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MoeUltPagmto {
            get {
                return this.moeUltPagmtoField;
            }
            set {
                this.moeUltPagmtoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Consultar_SyncCompletedEventHandler(object sender, Consultar_SyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Consultar_SyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Consultar_SyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConsultarResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConsultarResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591