IF NOT EXISTS ( 
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA = 'dbo' 
      AND TABLE_NAME = 'TB_EC_LOG_SIC_REBATE_RETROATIVO'
)
BEGIN
    CREATE TABLE [dbo].[TB_EC_LOG_SIC_REBATE_RETROATIVO] (
        [NR_SEQ_LOG_REBATE_RETROATIVO] [int] IDENTITY(1,1) NOT NULL,
        [NR_SEQ_APLICACAO_REBATE_RETROATIVO] [int] NOT NULL,
        [NR_SEQ_MODULO_REBATE_RETROATIVO] [int] NOT NULL,
        [NR_SEQ_ENTIDADE_REBATE_RETROATIVO] [int] NOT NULL,
        [DT_LOG_DATETIME_REBATE_RETROATIVO] [datetime] NOT NULL,
        [CD_LOG_USUARIO_REBATE_RETROATIVO]  [nvarchar](200) NULL, 
        [XML_LOG_DETALHE_REBATE_RETROATIVO] [nvarchar](MAX) NULL,
        CONSTRAINT [PK_TB_EC_LOG_SIC_REBATE_RETROATIVO] PRIMARY KEY CLUSTERED (
            [NR_SEQ_LOG_REBATE_RETROATIVO] ASC
        ) WITH (
            PAD_INDEX = OFF, 
            STATISTICS_NORECOMPUTE = OFF, 
            IGNORE_DUP_KEY = OFF, 
            ALLOW_ROW_LOCKS = ON, 
            ALLOW_PAGE_LOCKS = ON
        ) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

    PRINT 'Tabela TB_EC_LOG_SIC_REBATE_RETROATIVO criada com sucesso.';
END
ELSE
BEGIN
    PRINT 'A tabela TB_EC_LOG_SIC_REBATE_RETROATIVO já existe.';
END;